
package com.alignmentsystems.CountryCodes;

/**
 * 
 * @author John.Greenan
 * @see https://www.iso.org/obp/ui/#search
 * @since 6th August 2018
 */
public enum ISO3166 {
	AF("Afghanistan","Afghanistan (l')","AF","AFG",4),
	AX("Åland Islands","Åland(les Îles)","AX","ALA",248),
	AL("Albania","Albanie (l')","AL","ALB",8),
	DZ("Algeria","Algérie (l')","DZ","DZA",12),
	AS("American Samoa","Samoa américaines (les)","AS","ASM",16),
	AD("Andorra","Andorre (l')","AD","AND",20),
	AO("Angola","Angola (l')","AO","AGO",24),
	AI("Anguilla","Anguilla","AI","AIA",660),
	AQ("Antarctica","Antarctique (l')","AQ","ATA",10),
	AG("Antigua and Barbuda","Antigua-et-Barbuda","AG","ATG",28),
	AR("Argentina","Argentine (l')","AR","ARG",32),
	AM("Armenia","Arménie (l')","AM","ARM",51),
	AW("Aruba","Aruba","AW","ABW",533),
	AU("Australia","Australie (l')","AU","AUS",36),
	AT("Austria","Autriche (l')","AT","AUT",40),
	AZ("Azerbaijan","Azerbaïdjan (l')","AZ","AZE",31),
	BS("Bahamas (the)","Bahamas (les)","BS","BHS",44),
	BH("Bahrain","Bahreïn","BH","BHR",48),
	BD("Bangladesh","Bangladesh (le)","BD","BGD",50),
	BB("Barbados","Barbade (la)","BB","BRB",52),
	BY("Belarus","Bélarus (le)","BY","BLR",112),
	BE("Belgium","Belgique (la)","BE","BEL",56),
	BZ("Belize","Belize (le)","BZ","BLZ",84),
	BJ("Benin","Bénin (le)","BJ","BEN",204),
	BM("Bermuda","Bermudes (les)","BM","BMU",60),
	BT("Bhutan","Bhoutan (le)","BT","BTN",64),
	BO("Bolivia (Plurinational State of)","Bolivie (État plurinational de)","BO","BOL",68),
	BQ("Bonaire, Sint Eustatius and Saba","Bonaire, Saint-Eustache et Saba","BQ","BES",535),
	BA("Bosnia and Herzegovina","Bosnie-Herzégovine (la)","BA","BIH",70),
	BW("Botswana","Botswana (le)","BW","BWA",72),
	BV("Bouvet Island","Bouvet (l'Île)","BV","BVT",74),
	BR("Brazil","Brésil (le)","BR","BRA",76),
	IO("British Indian Ocean Territory (the)","Indien (le Territoire britannique de l'océan)","IO","IOT",86),
	BN("Brunei Darussalam","Brunéi Darussalam (le)","BN","BRN",96),
	BG("Bulgaria","Bulgarie (la)","BG","BGR",100),
	BF("Burkina Faso","Burkina Faso (le)","BF","BFA",854),
	BI("Burundi","Burundi (le)","BI","BDI",108),
	CV("Cabo Verde","Cabo Verde","CV","CPV",132),
	KH("Cambodia","Cambodge (le)","KH","KHM",116),
	CM("Cameroon","Cameroun (le)","CM","CMR",120),
	CA("Canada","Canada (le)","CA","CAN",124),
	KY("Cayman Islands (the)","Caïmans (les Îles)","KY","CYM",136),
	CF("Central African Republic (the)","République centrafricaine (la)","CF","CAF",140),
	TD("Chad","Tchad (le)","TD","TCD",148),
	CL("Chile","Chili (le)","CL","CHL",152),
	CN("China","Chine (la)","CN","CHN",156),
	CX("Christmas Island","Christmas (l'Île)","CX","CXR",162),
	CC("Cocos (Keeling) Islands (the)","Cocos (les Îles)/ Keeling (les Îles)","CC","CCK",166),
	CO("Colombia","Colombie (la)","CO","COL",170),
	KM("Comoros (the)","Comores (les)","KM","COM",174),
	CD("Congo (the Democratic Republic of the)","Congo (la République démocratique du)","CD","COD",180),
	CG("Congo (the)","Congo (le)","CG","COG",178),
	CK("Cook Islands (the)","Cook (les Îles)","CK","COK",184),
	CR("Costa Rica","Costa Rica (le)","CR","CRI",188),
	CI("Côte d'Ivoire","Côte d'Ivoire (la)","CI","CIV",384),
	HR("Croatia","Croatie (la)","HR","HRV",191),
	CU("Cuba","Cuba","CU","CUB",192),
	CW("Curaçao","Curaçao","CW","CUW",531),
	CY("Cyprus","Chypre","CY","CYP",196),
	CZ("Czechia","Tchéquie (la)","CZ","CZE",203),
	DK("Denmark","Danemark (le)","DK","DNK",208),
	DJ("Djibouti","Djibouti","DJ","DJI",262),
	DM("Dominica","Dominique (la)","DM","DMA",212),
	DO("Dominican Republic (the)","dominicaine (la République)","DO","DOM",214),
	EC("Ecuador","Équateur (l')","EC","ECU",218),
	EG("Egypt","Égypte (l')","EG","EGY",818),
	SV("El Salvador","El Salvador","SV","SLV",222),
	GQ("Equatorial Guinea","Guinée équatoriale (la)","GQ","GNQ",226),
	ER("Eritrea","Érythrée (l')","ER","ERI",232),
	EE("Estonia","Estonie (l')","EE","EST",233),
	SZ("Eswatini","Eswatini (l')","SZ","SWZ",748),
	ET("Ethiopia","Éthiopie (l')","ET","ETH",231),
	FK("Falkland Islands","Falkland","FK","FLK",238),
	FO("Faroe Islands (the)","Féroé (les Îles)","FO","FRO",234),
	FJ("Fiji","Fidji (les)","FJ","FJI",242),
	FI("Finland","Finlande (la)","FI","FIN",246),
	FR("France","France (la)","FR","FRA",250),
	GF("French Guiana","Guyane française (la )","GF","GUF",254),
	PF("French Polynesia","Polynésie française (la)","PF","PYF",258),
	TF("French Southern Territories (the)","Terres australes françaises (les)","TF","ATF",260),
	GA("Gabon","Gabon (le)","GA","GAB",266),
	GM("Gambia (the)","Gambie (la)","GM","GMB",270),
	GE("Georgia","Géorgie (la)","GE","GEO",268),
	DE("Germany","Allemagne (l')","DE","DEU",276),
	GH("Ghana","Ghana (le)","GH","GHA",288),
	GI("Gibraltar","Gibraltar","GI","GIB",292),
	GR("Greece","Grèce (la)","GR","GRC",300),
	GL("Greenland","Groenland (le)","GL","GRL",304),
	GD("Grenada","Grenade (la)","GD","GRD",308),
	GP("Guadeloupe","Guadeloupe (la)","GP","GLP",312),
	GU("Guam","Guam","GU","GUM",316),
	GT("Guatemala","Guatemala (le)","GT","GTM",320),
	GG("Guernsey","Guernesey","GG","GGY",831),
	GN("Guinea","Guinée (la)","GN","GIN",324),
	GW("Guinea-Bissau","Guinée-Bissau (la)","GW","GNB",624),
	GY("Guyana","Guyana (le)","GY","GUY",328),
	HT("Haiti","Haïti","HT","HTI",332),
	HM("Heard Island and McDonald Islands","Heard-et-Îles MacDonald (l'Île)","HM","HMD",334),
	VA("Holy See (the)","Saint-Siège (le)","VA","VAT",336),
	HN("Honduras","Honduras (le)","HN","HND",340),
	HK("Hong Kong","Hong Kong","HK","HKG",344),
	HU("Hungary","Hongrie (la)","HU","HUN",348),
	IS("Iceland","Islande (l')","IS","ISL",352),
	IN("India","Inde (l')","IN","IND",356),
	ID("Indonesia","Indonésie (l')","ID","IDN",360),
	IR("Iran (Islamic Republic of)","Iran (République Islamique d')","IR","IRN",364),
	IQ("Iraq","Iraq (l')","IQ","IRQ",368),
	IE("Ireland","Irlande (l')","IE","IRL",372),
	IM("Isle of Man","Île de Man","IM","IMN",833),
	IL("Israel","Israël","IL","ISR",376),
	IT("Italy","Italie (l')","IT","ITA",380),
	JM("Jamaica","Jamaïque (la)","JM","JAM",388),
	JP("Japan","Japon (le)","JP","JPN",392),
	JE("Jersey","Jersey","JE","JEY",832),
	JO("Jordan","Jordanie (la)","JO","JOR",400),
	KZ("Kazakhstan","Kazakhstan (le)","KZ","KAZ",398),
	KE("Kenya","Kenya (le)","KE","KEN",404),
	KI("Kiribati","Kiribati","KI","KIR",296),
	KP("Korea (the Democratic People's Republic of)","Corée (la République populaire démocratique de)","KP","PRK",408),
	KR("Korea (the Republic of)","Corée (la République de)","KR","KOR",410),
	KW("Kuwait","Koweït (le)","KW","KWT",414),
	KG("Kyrgyzstan","Kirghizistan (le)","KG","KGZ",417),
	LA("Lao People's Democratic Republic (the)","Lao, République démocratique populaire","LA","LAO",418),
	LV("Latvia","Lettonie (la)","LV","LVA",428),
	LB("Lebanon","Liban (le)","LB","LBN",422),
	LS("Lesotho","Lesotho (le)","LS","LSO",426),
	LR("Liberia","Libéria (le)","LR","LBR",430),
	LY("Libya","Libye (la)","LY","LBY",434),
	LI("Liechtenstein","Liechtenstein (le)","LI","LIE",438),
	LT("Lithuania","Lituanie (la)","LT","LTU",440),
	LU("Luxembourg","Luxembourg (le)","LU","LUX",442),
	MO("Macao","Macao","MO","MAC",446),
	MK("Macedonia (the former Yugoslav Republic of)","Macédoine (l'ex‑République yougoslave de)","MK","MKD",807),
	MG("Madagascar","Madagascar","MG","MDG",450),
	MW("Malawi","Malawi (le)","MW","MWI",454),
	MY("Malaysia","Malaisie (la)","MY","MYS",458),
	MV("Maldives","Maldives (les)","MV","MDV",462),
	ML("Mali","Mali (le)","ML","MLI",466),
	MT("Malta","Malte","MT","MLT",470),
	MH("Marshall Islands (the)","Marshall (Îles)","MH","MHL",584),
	MQ("Martinique","Martinique (la)","MQ","MTQ",474),
	MR("Mauritania","Mauritanie (la)","MR","MRT",478),
	MU("Mauritius","Maurice","MU","MUS",480),
	YT("Mayotte","Mayotte","YT","MYT",175),
	MX("Mexico","Mexique (le)","MX","MEX",484),
	FM("Micronesia (Federated States of)","Micronésie (États fédérés de)","FM","FSM",583),
	MD("Moldova (the Republic of)","Moldova, République de","MD","MDA",498),
	MC("Monaco","Monaco","MC","MCO",492),
	MN("Mongolia","Mongolie (la)","MN","MNG",496),
	ME("Montenegro","Monténégro (le)","ME","MNE",499),
	MS("Montserrat","Montserrat","MS","MSR",500),
	MA("Morocco","Maroc (le)","MA","MAR",504),
	MZ("Mozambique","Mozambique (le)","MZ","MOZ",508),
	MM("Myanmar","Myanmar (le)","MM","MMR",104),
	NA("Namibia","Namibie (la)","NA","NAM",516),
	NR("Nauru","Nauru","NR","NRU",520),
	NP("Nepal","Népal (le)","NP","NPL",524),
	NL("Netherlands (the)","Pays-Bas (les)","NL","NLD",528),
	NC("New Caledonia","Nouvelle-Calédonie (la)","NC","NCL",540),
	NZ("New Zealand","Nouvelle-Zélande (la)","NZ","NZL",554),
	NI("Nicaragua","Nicaragua (le)","NI","NIC",558),
	NE("Niger (the)","Niger (le)","NE","NER",562),
	NG("Nigeria","Nigéria (le)","NG","NGA",566),
	NU("Niue","Niue","NU","NIU",570),
	NF("Norfolk Island","Norfolk (l'Île)","NF","NFK",574),
	MP("Northern Mariana Islands (the)","Mariannes du Nord (les Îles)","MP","MNP",580),
	NO("Norway","Norvège (la)","NO","NOR",578),
	OM("Oman","Oman","OM","OMN",512),
	PK("Pakistan","Pakistan (le)","PK","PAK",586),
	PW("Palau","Palaos (les)","PW","PLW",585),
	PS("Palestine, State of","Palestine, État de","PS","PSE",275),
	PA("Panama","Panama (le)","PA","PAN",591),
	PG("Papua New Guinea","Papouasie-Nouvelle-Guinée (la)","PG","PNG",598),
	PY("Paraguay","Paraguay (le)","PY","PRY",600),
	PE("Peru","Pérou (le)","PE","PER",604),
	PH("Philippines (the)","Philippines (les)","PH","PHL",608),
	PN("Pitcairn","Pitcairn","PN","PCN",612),
	PL("Poland","Pologne (la)","PL","POL",616),
	PT("Portugal","Portugal (le)","PT","PRT",620),
	PR("Puerto Rico","Porto Rico","PR","PRI",630),
	QA("Qatar","Qatar (le)","QA","QAT",634),
	RE("Réunion","Réunion (La)","RE","REU",638),
	RO("Romania","Roumanie (la)","RO","ROU",642),
	RU("Russian Federation (the)","Russie (la Fédération de)","RU","RUS",643),
	RW("Rwanda","Rwanda (le)","RW","RWA",646),
	BL("Saint Barthélemy","Saint-Barthélemy","BL","BLM",652),
	SH("Saint Helena, Ascension and Tristan da Cunha","Sainte-Hélène, Ascension et Tristan da Cunha","SH","SHN",654),
	KN("Saint Kitts and Nevis","Saint-Kitts-et-Nevis","KN","KNA",659),
	LC("Saint Lucia","Sainte-Lucie","LC","LCA",662),
	MF("Saint Martin (French part)","Saint-Martin (partie française)","MF","MAF",663),
	PM("Saint Pierre and Miquelon","Saint-Pierre-et-Miquelon","PM","SPM",666),
	VC("Saint Vincent and the Grenadines","Saint-Vincent-et-les Grenadines","VC","VCT",670),
	WS("Samoa","Samoa (le)","WS","WSM",882),
	SM("San Marino","Saint-Marin","SM","SMR",674),
	ST("Sao Tome and Principe","Sao Tomé-et-Principe","ST","STP",678),
	SA("Saudi Arabia","Arabie saoudite (l')","SA","SAU",682),
	SN("Senegal","Sénégal (le)","SN","SEN",686),
	RS("Serbia","Serbie (la)","RS","SRB",688),
	SC("Seychelles","Seychelles (les)","SC","SYC",690),
	SL("Sierra Leone","Sierra Leone (la)","SL","SLE",694),
	SG("Singapore","Singapour","SG","SGP",702),
	SX("Sint Maarten (Dutch part)","Saint-Martin (partie néerlandaise)","SX","SXM",534),
	SK("Slovakia","Slovaquie (la)","SK","SVK",703),
	SI("Slovenia","Slovénie (la)","SI","SVN",705),
	SB("Solomon Islands","Salomon (Îles)","SB","SLB",90),
	SO("Somalia","Somalie (la)","SO","SOM",706),
	ZA("South Africa","Afrique du Sud (l')","ZA","ZAF",710),
	GS("South Georgia and the South Sandwich Islands","Géorgie du Sud-et-les Îles Sandwich du Sud (la)","GS","SGS",239),
	SS("South Sudan","Soudan du Sud (le)","SS","SSD",728),
	ES("Spain","Espagne (l')","ES","ESP",724),
	LK("Sri Lanka","Sri Lanka","LK","LKA",144),
	SD("Sudan (the)","Soudan (le)","SD","SDN",729),
	SR("Suriname","Suriname (le)","SR","SUR",740),
	SJ("Svalbard and Jan Mayen","Svalbard et l'Île Jan Mayen (le)","SJ","SJM",744),
	SE("Sweden","Suède (la)","SE","SWE",752),
	CH("Switzerland","Suisse (la)","CH","CHE",756),
	SY("Syrian Arab Republic","République arabe syrienne (la)","SY","SYR",760),
	TW("Taiwan (Province of China)","Taïwan (Province de Chine)","TW","TWN",158),
	TJ("Tajikistan","Tadjikistan (le)","TJ","TJK",762),
	TZ("Tanzania, United Republic of","Tanzanie, République-Unie de","TZ","TZA",834),
	TH("Thailand","Thaïlande (la)","TH","THA",764),
	TL("Timor-Leste","Timor-Leste (le)","TL","TLS",626),
	TG("Togo","Togo (le)","TG","TGO",768),
	TK("Tokelau","Tokelau (les)","TK","TKL",772),
	TO("Tonga","Tonga (les)","TO","TON",776),
	TT("Trinidad and Tobago","Trinité-et-Tobago (la)","TT","TTO",780),
	TN("Tunisia","Tunisie (la)","TN","TUN",788),
	TR("Turkey","Turquie (la)","TR","TUR",792),
	TM("Turkmenistan","Turkménistan (le)","TM","TKM",795),
	TC("Turks and Caicos Islands (the)","Turks-et-Caïcos (les Îles)","TC","TCA",796),
	TV("Tuvalu","Tuvalu (les)","TV","TUV",798),
	UG("Uganda","Ouganda (l')","UG","UGA",800),
	UA("Ukraine","Ukraine (l')","UA","UKR",804),
	AE("United Arab Emirates (the)","Émirats arabes unis (les)","AE","ARE",784),
	GB("United Kingdom of Great Britain and Northern Ireland (the)","Royaume-Uni de Grande-Bretagne et d'Irlande du Nord (le)","GB","GBR",826),
	UM("United States Minor Outlying Islands (the)","Îles mineures éloignées des États-Unis (les)","UM","UMI",581),
	US("United States of America (the)","États-Unis d'Amérique (les)","US","USA",840),
	UY("Uruguay","Uruguay (l')","UY","URY",858),
	UZ("Uzbekistan","Ouzbékistan (l')","UZ","UZB",860),
	VU("Vanuatu","Vanuatu (le)","VU","VUT",548),
	VE("Venezuela (Bolivarian Republic of)","Venezuela (République bolivarienne du)","VE","VEN",862),
	VN("Viet Nam","Viet Nam (le)","VN","VNM",704),
	VG("Virgin Islands (British)","Vierges britanniques (les Îles)","VG","VGB",92),
	VI("Virgin Islands (U.S.)","Vierges des États-Unis (les Îles)","VI","VIR",850),
	WF("Wallis and Futuna","Wallis-et-Futuna ","WF","WLF",876),
	EH("Western Sahara*","Sahara occidental (le)*","EH","ESH",732),
	YE("Yemen","Yémen (le)","YE","YEM",887),
	ZM("Zambia","Zambie (la)","ZM","ZMB",894),
	ZW("Zimbabwe","Zimbabwe (le)","ZW","ZWE",716);
	
	public final String CountryNameEnglish;
	public final String CountryNameFrench;
	public final String TwoLetterCode;
	public final String ThreeLetterCode;
	public final long NumberCode;
	ISO3166(String CountryNameEnglish,String CountryNameFrench,String TwoLetterCode, String ThreeLetterCode,long NumberCode) {
		this.CountryNameEnglish=CountryNameEnglish;
		this.CountryNameFrench=CountryNameFrench;
		this.TwoLetterCode=TwoLetterCode;
		this.ThreeLetterCode=ThreeLetterCode;
		this.NumberCode=NumberCode;
	}
}


